// AUTO-GENERATED by server/build-sim.mjs — DO NOT EDIT (source: shared/config.js)
// Re-run `npm run build:sim` in server/ after changing the source.

// Single source of truth: shared/config.js, served at /js/config.js as a
// classic script that sets window.CONFIG before any module loads.
export default window.CONFIG;
