// AUTO-GENERATED by server/build-sim.mjs — DO NOT EDIT (source: server/src/game.js)
// Re-run `npm run build:sim` in server/ after changing the source.

// server/src/game.js — Authoritative 60Hz game loop

'use strict';

import CONFIG from './config.js';
import { getArena } from './arenas.js';
import { updateShip, resolveShipCollisions, createShip } from './physics.js';
import { fireBullets, updateBullets, updateMines, explode } from './weapons.js';
import { updatePowerups, checkPickups, createPowerup } from './powerups.js';
import { createTurret, updateTurrets, applyBlackholes, applyGravity, updateWave, updateWormholes,
        createDoorState, toggleDoorGroup, updateDoors, createPiston, updatePistons,
        createPathVehicle, updatePathVehicles } from './hazards.js';
import { createAIShip, updateAI } from './enemies.js';
import { getMission } from './missions.js';
const { TILE } = CONFIG;

const SOLO_AI_COUNT = { easy: 1, medium: 2, hard: 3 };
const SOLO_SCORE_MULT = { easy: 1, medium: 2, hard: 3 };

// Endless mode: seconds between clearing a wave and spawning the next
const WAVE_DELAY = 3.0;
// Endless score: kills + bonus per wave cleared
const WAVE_SCORE_BONUS = 5;

/**
 * Endless wave composition: AI count ramps 1 → 3, difficulty ramps
 * easy (waves 1-3) → medium (4-6) → hard (7+).
 */
function waveComposition(wave) {
  const count      = Math.min(1 + Math.floor((wave - 1) / 2), 3);
  const difficulty = wave <= 3 ? 'easy' : wave <= 6 ? 'medium' : 'hard';
  return { count, difficulty };
}

const nowMs = () => performance.now() * 1e6;

const TICK_MS = 1000 / CONFIG.TICK_RATE;  // ~16.67ms

class Game {
  constructor(room, players, broadcast, options = {}) {
    this.room      = room;
    this.broadcast = broadcast;
    this.soloMode  = options.soloMode  || false;
    this.soloDiff  = options.difficulty || 'easy';

    // Solo sub-mode: 'skirmish' (default) | 'mission' | 'endless'
    this.soloGameMode = options.mode || 'skirmish';
    this.mission      = null;
    if (this.soloMode && this.soloGameMode === 'mission') {
      this.mission = getMission(options.missionId);
      if (!this.mission) this.soloGameMode = 'skirmish';  // unknown mission → skirmish
    }
    if (this.mission) this.soloDiff = this.mission.difficulty;

    // Pick arena: mission forces its own arena, otherwise by id / 'random'
    this.arena = getArena(this.mission ? this.mission.arenaId : (options.arenaId || 'random'));

    // Create ships
    this.ships = {};
    players.forEach((p, idx) => {
      const sp = this.arena.spawnPoints[idx % this.arena.spawnPoints.length];
      this.ships[p.id] = createShip(p, sp, idx);
      // Stat tracking for the GAME OVER screen (humans only)
      this.ships[p.id].shotsFired = 0;
      this.ships[p.id].shotsHit   = 0;
    });
    this._startTime = Date.now();

    // Solo mode: spawn AI ships
    this.aiShips = [];
    if (this.soloMode) {
      this.playerLives  = this.mission ? this.mission.lives : 3;
      this.aiKilled     = 0;    // AI destroyed (mission progress / endless kills)
      this.wave         = 1;    // endless wave number
      this.waveDelay    = 0;    // >0 while waiting to spawn the next wave
      this.missionTimer = this.mission && this.mission.objective.type === 'survive'
        ? this.mission.objective.seconds
        : 0;

      const aiCount = this.soloGameMode === 'endless'
        ? waveComposition(1).count
        : this.mission
          ? this.mission.aiCount
          : (SOLO_AI_COUNT[this.soloDiff] || 1);
      this._spawnAIWave(aiCount, this.soloGameMode === 'endless'
        ? waveComposition(1).difficulty
        : this.soloDiff, players.length);
    }

    this.bullets    = [];
    this.mines      = [];
    this.powerups   = [];
    this.stickies   = [];   // sticky bombs attaccate (F11a)
    this.lazerTraps = [];   // tripwire laser (F11a)

    // ── Environmental hazards (from arena generation) ──────
    this.hazards    = this.arena.hazards;
    this.turrets    = this.hazards.turrets.map((d, i) => createTurret(d, 'turret-' + i));
    this.blackholes = this.hazards.blackholes;
    this.gravity    = this.hazards.gravity    || [];
    this.wormholes  = this.hazards.wormholes  || [];
    this.waveState  = this.hazards.wave
      ? { ...this.hazards.wave, timer: 6, active: null }
      : null;
    // F7b: CA doors + trigger buttons, one-way walls, pistons
    this.doorTiles  = this.hazards.doors   || [];
    this.buttons    = this.hazards.buttons || [];
    this.doorState  = createDoorState(this.doorTiles);
    this.pistons    = (this.hazards.pistons || []).map(d => createPiston(d));
    // F7c: path vehicles (CA PATHVEHICLES)
    this.pathVehicles = (this.hazards.pathVehicles || []).map(d => createPathVehicle(d));
    // Arena-placed proximity mines: ownerless (no kill credit), pre-armed.
    // Negative ids never collide with weapon-laid mine ids.
    let hazardMineId = -1;
    for (const m of this.hazards.mines) {
      this.mines.push({ id: hazardMineId--, x: m.x, y: m.y, ownerId: null, armTimer: 0 });
    }
    this.events     = [];   // accumulated per-tick events to broadcast
    this.tickCount  = 0;
    this.running    = false;
    this.roundOver  = false;

    // Input buffer: latest input per human player
    this.inputBuffer = {};
    for (const p of players) {
      this.inputBuffer[p.id] = { up:false, down:false, left:false, right:false, fire:false, dash:false, dodge:false, switchWeapon:false };
    }

    // Power-up spawn timers (one per spot)
    this.spawnTimers = this.arena.powerupSpots.map(() => 5 + Math.random() * 10);

    this._intervalId  = null;
    this._lastTime    = null;
    this._endTimeout  = null;
  }

  _arenaMessage() {
    return {
      type:         'arena',
      tiles:        this.arena.tiles,
      wallHP:       this.arena.wallHP,
      theme:        this.arena.theme,
      spawnPoints:  this.arena.spawnPoints,
      powerupSpots: this.arena.powerupSpots,
      oneWayDir:    this.arena.oneWayDir || null,
      hazards: {
        mines:      this.hazards.mines,
        turrets:    this.turrets.map(t => ({ id: t.id, type: t.type, x: t.x, y: t.y })),
        blackholes: this.blackholes,
        gravity:    this.gravity,
        wormholes:  this.wormholes,
        wave:       this.hazards.wave,
        doors:      this.doorTiles,
        buttons:    this.buttons,
        oneWays:    this.hazards.oneWays || [],
        pistons:    this.pistons.map(p => ({ x: p.ox, y: p.oy, axis: p.axis })),
        pathVehicles: (this.hazards.pathVehicles || []).map(v => ({ points: v.points, speed: v.speed })),
      },
    };
  }

  /** Send the arena message to a single target (F5c: rejoin mid-game). */
  sendArena(targetFn) {
    targetFn(this._arenaMessage());
  }

  start() {
    this.running  = true;
    this._lastTime = nowMs();

    // Send arena to all clients
    this.broadcast(this._arenaMessage());

    this._intervalId = setInterval(() => this._tick(), TICK_MS);
  }

  stop() {
    this.running = false;
    if (this._intervalId) {
      clearInterval(this._intervalId);
      this._intervalId = null;
    }
    if (this._endTimeout) {
      clearTimeout(this._endTimeout);
      this._endTimeout = null;
    }
  }

  receiveInput(playerId, msg) {
    if (!this.inputBuffer[playerId]) return;
    const keys = msg.keys || {};
    const buf  = this.inputBuffer[playerId];
    buf.up           = !!keys.up;
    buf.down         = !!keys.down;
    buf.left         = !!keys.left;
    buf.right        = !!keys.right;
    buf.fire         = !!keys.fire;
    buf.dash         = !!keys.dash;
    buf.dodge        = !!keys.dodge;
    buf.switchWeapon = !!keys.switchWeapon;
    buf.weaponSelect = keys.weaponSelect || 0;
  }

  /**
   * Spawn (or recycle) `count` AI ships at `difficulty`. Existing AI slots
   * are reused; slots beyond `count` stay dead. playerCount offsets the
   * spawn-point index so AI don't spawn on top of humans.
   */
  _spawnAIWave(count, difficulty, playerCount = 1) {
    for (let i = 0; i < count; i++) {
      const spIdx  = (playerCount + i) % this.arena.spawnPoints.length;
      const sp     = this.arena.spawnPoints[spIdx];
      const shipId = Math.floor(Math.random() * CONFIG.SHIPS.length);
      let ai = this.aiShips[i];
      if (!ai) {
        ai = createAIShip('ai-' + i, sp, shipId, difficulty);
        this.aiShips.push(ai);
        this.ships[ai.id] = ai;
      } else {
        Object.assign(ai, createAIShip(ai.id, sp, shipId, difficulty));
      }
    }
    for (let i = count; i < this.aiShips.length; i++) {
      this.aiShips[i].alive = false;
      this.aiShips[i].respawnTimer = 9999;
    }
  }

  /** Respawn one dead AI ship on a random spawn point (mid-wave modes). */
  _respawnAI(ai) {
    const sp = this.arena.spawnPoints[Math.floor(Math.random() * this.arena.spawnPoints.length)];
    const difficulty = this.soloGameMode === 'endless'
      ? waveComposition(this.wave).difficulty
      : this.soloDiff;
    const shipId = Math.floor(Math.random() * CONFIG.SHIPS.length);
    Object.assign(ai, createAIShip(ai.id, sp, shipId, difficulty));
  }

  /** Should a just-killed AI respawn? Only in mission modes that need it. */
  _aiShouldRespawn() {
    if (!this.mission) return false;  // skirmish & endless: waves / no respawn
    const obj = this.mission.objective;
    if (obj.type === 'eliminate') {
      const alive = this.aiShips.filter(a => a.alive).length;
      return this.aiKilled + alive < obj.kills;
    }
    return true;  // survive / turrets: keep the pressure on
  }

  _tick() {
    if (!this.running) return;

    const now = nowMs();
    const dt  = Math.min(Number(now - this._lastTime) / 1e9, 0.05); // cap at 50ms
    this._lastTime = now;
    this.tickCount++;

    this.events = [];

    if (!this.roundOver) {
      this._update(dt);
    }

    // Broadcast state every STATE_INTERVAL ticks (20 Hz)
    if (this.tickCount % CONFIG.STATE_INTERVAL === 0) {
      this._broadcastState();
    }

    // Broadcast accumulated events immediately
    for (const ev of this.events) {
      this.broadcast(ev);
    }
  }

  _update(dt) {
    // ── Process weapon switching (human ships only) ────────
    for (const [id, ship] of Object.entries(this.ships)) {
      if (ship.isAI) continue;
      const input = this.inputBuffer[id];
      if (!input) continue;
      const owned = Object.keys(ship.weapons).map(Number).sort((a, b) => a - b);
      // Selezione diretta con tasti 1-9 (n-esima arma posseduta)
      if (input.weaponSelect > 0 && input.weaponSelect <= owned.length && ship.alive) {
        ship.weapon = owned[input.weaponSelect - 1];
        input.weaponSelect = 0;
      }
      // Q: cicla le armi possedute
      if (input.switchWeapon && !input._prevSwitchWeapon && ship.alive) {
        const idx = owned.indexOf(ship.weapon);
        ship.weapon = owned[(idx + 1) % owned.length];
      }
      input._prevSwitchWeapon = input.switchWeapon;
    }

    // ── Update human ships ─────────────────────────────────
    for (const [id, ship] of Object.entries(this.ships)) {
      if (ship.isAI) continue;
      const input = this.inputBuffer[id] || {};
      updateShip(ship, input, dt, this.arena);
      if (ship.acidKill) {
        this._killShip(ship, null, null);
      }
    }

    // ── Update AI ships ────────────────────────────────────
    if (this.soloMode && this.aiShips.length > 0) {
      const aiBullets = updateAI(this.aiShips, this.ships, this.arena, dt);
      this.bullets.push(...aiBullets);
      // Check acid kills on AI ships
      for (const ai of this.aiShips) {
        if (ai.alive && ai.acidKill) {
          this._killShip(ai, null, null);
        }
      }
      // Mid-wave AI respawns (mission modes that allow it)
      for (const ai of this.aiShips) {
        if (ai.alive || ai.respawnTimer >= 9999) continue;
        ai.respawnTimer -= dt;
        if (ai.respawnTimer <= 0) this._respawnAI(ai);
      }
    }

    // ── Solo: mission timer + endless wave progression ──────
    if (this.soloMode && !this.roundOver) {
      if (this.mission && this.mission.objective.type === 'survive' && this.missionTimer > 0) {
        this.missionTimer -= dt;
      }
      if (this.soloGameMode === 'endless') {
        if (this.aiShips.some(ai => ai.alive)) {
          this.waveDelay = 0;
        } else {
          if (this.waveDelay <= 0) this.waveDelay = WAVE_DELAY;
          this.waveDelay -= dt;
          if (this.waveDelay <= 0) {
            this.wave++;
            const { count, difficulty } = waveComposition(this.wave);
            this._spawnAIWave(count, difficulty);
            this.events.push({ type: 'event', kind: 'wave_start', wave: this.wave });
          }
        }
      }
    }

    // ── Ship-ship collision ────────────────────────────────
    resolveShipCollisions(this.ships);

    // ── Fire bullets (human ships only; AI fires via updateAI) ──
    for (const [id, ship] of Object.entries(this.ships)) {
      if (ship.isAI) continue;
      const input = this.inputBuffer[id] || {};
      const { bullets, beams, mines, traps, blasts } = fireBullets(ship, input, { ships: this.ships, arena: this.arena });
      ship.shotsFired += bullets.length + beams.length + mines.length + traps.length + blasts.length;
      this.bullets.push(...bullets);
      this._addMines(mines);
      this._handleBeams(beams);
      for (const t of traps) this._addLazerTrap(t);
      for (const b of blasts) this._explodeAt(b.x, b.y, b.radius, b.damage, b.ownerId);
    }

    // ── Update bullets ────────────────────────────────────
    const { survived, events: bulletEvents } = updateBullets(
      this.bullets, this.ships, this.arena, dt, this.turrets,
      [...this.pistons, ...this.pathVehicles]   // blocchi mobili solidi (F7b/F7c)
    );
    this.bullets = survived;

    for (const ev of bulletEvents) {
      this._processBulletEvent(ev);
    }

    // ── Update mines ──────────────────────────────────────
    const { survived: minesSurvived, events: mineEvents } = updateMines(
      this.mines, this.ships, dt
    );
    this.mines = minesSurvived;

    for (const ev of mineEvents) {
      if (ev.kind === 'mine_explode') {
        this._explodeAt(ev.x, ev.y, CONFIG.MINE.AOE_RADIUS, CONFIG.MINE.AOE_DAMAGE, ev.mine.ownerId);
      }
    }

    // ── Sticky bombs: fuse e detonazione (F11a) ───────────
    for (const s of this.stickies) s.timer -= dt;
    const detonating = this.stickies.filter(s => s.timer <= 0);
    this.stickies = this.stickies.filter(s => s.timer > 0);
    for (const s of detonating) {
      let ex = s.x, ey = s.y;
      if (s.targetId && this.ships[s.targetId]) {
        ex = this.ships[s.targetId].x;
        ey = this.ships[s.targetId].y;
      }
      if (ex !== undefined) this._explodeAt(ex, ey, s.aoe.radius, s.aoe.damage, s.ownerId);
    }

    // ── Lazer traps: danno a chi incrocia il raggio (F11a) ──
    const ltCfg = CONFIG.LAZERTRAP;
    this.lazerTraps = this.lazerTraps.filter(t => (t.timer -= dt) > 0);
    for (const t of this.lazerTraps) {
      for (const ship of Object.values(this.ships)) {
        if (!ship.alive || ship.id === t.ownerId) continue;
        const d = _distToSegment(ship.x, ship.y, t.x1, t.y1, t.x2, t.y2);
        if (d <= ltCfg.WIDTH + CONFIG.SHIP_RADIUS * 0.5) {
          this._applyDamage(ship, ltCfg.DPS * dt);
          ship.hitFlashTimer = 0.15;
          if (ship.shield <= 0) {
            ship.shield = 0;
            this._killShip(ship, t.ownerId, 14);
          }
        }
      }
    }

    // ── Update power-ups ──────────────────────────────────
    const { powerups: updatedPu, events: puEvents } = updatePowerups(
      this.powerups, this.spawnTimers, this.arena.powerupSpots, dt
    );
    this.powerups = updatedPu;

    const { powerups: afterPickup, events: pickupEvents } = checkPickups(
      this.powerups, this.ships
    );
    this.powerups = afterPickup;

    for (const ev of pickupEvents) {
      this.events.push({ type: 'event', ...ev });
    }

    // ── Update hazards ────────────────────────────────────
    // Turrets track and shoot ships
    const { bullets: turretBullets } = updateTurrets(this.turrets, this.ships, dt);
    this.bullets.push(...turretBullets);

    // Black holes pull and damage ships
    for (const { ship, dmg } of applyBlackholes(this.blackholes, this.ships, dt)) {
      this._damageEnvironment(ship, dmg);
    }

    // Gravity zones push ships (no damage)
    applyGravity(this.gravity, this.ships, dt);

    // Wormholes teleport ships between paired endpoints
    for (const ev of updateWormholes(this.wormholes, this.ships, dt).events) {
      this.events.push({ type: 'event', ...ev });
    }

    // Doors: advance open/close animation + tile solidity
    if (this.doorTiles.length > 0) {
      updateDoors(this.doorState, this.doorTiles, this.arena.tiles, this.ships, dt);
    }

    // Pistons: slide, push ships, crush against walls
    if (this.pistons.length > 0) {
      const { damages } = updatePistons(this.pistons, this.ships, this.arena, dt);
      for (const { ship, dmg } of damages) {
        this._damageEnvironment(ship, dmg);
      }
    }

    // F7c: path vehicles su binario (spingono/schiacciano come i pistoni)
    if (this.pathVehicles.length > 0) {
      const { damages } = updatePathVehicles(this.pathVehicles, this.ships, this.arena, dt);
      for (const { ship, dmg } of damages) {
        this._damageEnvironment(ship, dmg);
      }
    }

    // Periodic energy wave
    if (this.waveState) {
      const { damages, events: waveEvents } = updateWave(this.waveState, this.ships, this.arena, dt);
      for (const { ship, dmg } of damages) {
        this._damageEnvironment(ship, dmg);
      }
      for (const ev of waveEvents) {
        this.events.push({ type: 'event', ...ev });
      }
    }

    // ── Check round end ───────────────────────────────────
    this._checkRoundEnd();
  }

  _processBulletEvent(ev) {
    if (ev.kind === 'wall_hit') {
      // STICKY BOMB: si attacca al muro invece di danneggiarlo (F11a)
      if (ev.bullet.sticky) {
        this.stickies.push({
          x: ev.bullet.x, y: ev.bullet.y,
          timer: ev.bullet.sticky.fuse, aoe: ev.bullet.sticky.aoe,
          ownerId: ev.bullet.ownerId,
        });
        return;
      }
      // Damage destructible walls
      if (ev.tileType === TILE.WALL_DEST) {
        const hp = this.arena.wallHP[ev.ty][ev.tx];
        if (hp > 0) {
          const w    = CONFIG.WEAPONS[ev.bullet.weapon];
          const newHp = Math.max(0, hp - w.damage);
          this.arena.wallHP[ev.ty][ev.tx] = newHp;
          const state = newHp > 20 ? 'intact' : newHp > 0 ? 'damaged' : 'destroyed';
          if (newHp <= 0) {
            this.arena.tiles[ev.ty][ev.tx] = TILE.DEBRIS;
          }
          this.events.push({
            type: 'event',
            kind: 'wall_damage',
            tx: ev.tx, ty: ev.ty,
            hp: newHp,
            state,
          });
          if (newHp <= 0) {
            this.events.push({
              type: 'event',
              kind: 'explosion',
              x: ev.tx * CONFIG.TILE_SIZE + CONFIG.TILE_SIZE / 2,
              y: ev.ty * CONFIG.TILE_SIZE + CONFIG.TILE_SIZE / 2,
              size: 'medium',
            });
          }
        }
      } else if (ev.tileType === TILE.GLASS) {
        // Glass breaks in one hit
        this.arena.tiles[ev.ty][ev.tx] = TILE.DEBRIS;
        this.events.push({
          type: 'event', kind: 'wall_damage',
          tx: ev.tx, ty: ev.ty, hp: 0, state: 'destroyed',
        });
      }
      // Small spark for bullet wall impact
      this.events.push({
        type: 'event', kind: 'explosion',
        x: ev.bullet.x, y: ev.bullet.y, size: 'small',
      });
    }

    if (ev.kind === 'bullet_hit') {
      const ship = ev.ship;

      // STICKY BOMB: si attacca alla nave invece di danneggiarla subito (F11a)
      if (ev.bullet.sticky) {
        this.stickies.push({
          targetId: ship.id,
          timer: ev.bullet.sticky.fuse, aoe: ev.bullet.sticky.aoe,
          ownerId: ev.bullet.ownerId,
        });
        this.events.push({
          type: 'event', kind: 'explosion',
          x: ev.bullet.x, y: ev.bullet.y, size: 'small',
        });
        return;
      }

      this._applyDamage(ship, ev.bullet.damage);
      ship.hitFlashTimer = 0.15;

      // Accuracy tracking (human owners only)
      const owner = ev.bullet.ownerId ? this.ships[ev.bullet.ownerId] : null;
      if (owner && !owner.isAI) owner.shotsHit++;

      this.events.push({
        type: 'event', kind: 'explosion',
        x: ev.bullet.x, y: ev.bullet.y, size: 'small',
      });

      if (ship.shield <= 0) {
        ship.shield = 0;
        this._killShip(ship, ev.bullet.ownerId, ev.bullet.weapon);
      }
    }

    if (ev.kind === 'turret_hit') {
      this._damageTurret(ev.turret, ev.bullet.damage, ev.bullet.ownerId);
      this.events.push({
        type: 'event', kind: 'explosion',
        x: ev.bullet.x, y: ev.bullet.y, size: 'small',
      });
    }

    if (ev.kind === 'button_hit') {
      // Trigger button: toggle the linked door group (CA TRIGGERS, F7b)
      const btn = this.buttons.find(b => b.c === ev.tx && b.r === ev.ty);
      if (btn) {
        const open = toggleDoorGroup(this.doorState, btn.group);
        if (open !== null) {
          this.events.push({ type: 'event', kind: 'door', group: btn.group, open });
        }
        this.events.push({ type: 'event', kind: 'button_hit', x: btn.x, y: btn.y });
      }
      this.events.push({
        type: 'event', kind: 'explosion',
        x: ev.bullet.x, y: ev.bullet.y, size: 'small',
      });
    }

    if (ev.kind === 'piston_hit') {
      // Small spark for bullet impact on a piston block
      this.events.push({
        type: 'event', kind: 'explosion',
        x: ev.bullet.x, y: ev.bullet.y, size: 'small',
      });
    }

    // AoE warheads explode on ANY impact (wall, ship or turret), in addition
    // to the direct-hit damage above
    if (ev.bullet.aoe) {
      this._explodeAt(ev.bullet.x, ev.bullet.y, ev.bullet.aoe.radius, ev.bullet.aoe.damage, ev.bullet.ownerId);
    }
  }

  /**
   * Apply damage to a ship: pshieldPool absorbs first, overflow hits shield.
   */
  _applyDamage(ship, dmg) {
    let remaining = dmg;
    if (ship.pshieldPool > 0) {
      const absorbed = Math.min(ship.pshieldPool, remaining);
      ship.pshieldPool -= absorbed;
      remaining -= absorbed;
    }
    ship.shield -= remaining;
  }

  /**
   * Trigger an explosion at (x, y): damage every ship in radius
   * (owner included, Chase Ace 2 style) and broadcast the event.
   * Turrets caught in the blast take damage with the same falloff.
   */
  _explodeAt(x, y, radius, damage, ownerId) {
    const hits = explode(x, y, radius, damage, ownerId, this.ships);
    for (const { ship, dmg } of hits) {
      this._applyDamage(ship, dmg);
      ship.hitFlashTimer = 0.15;
      if (ship.shield <= 0) {
        ship.shield = 0;
        this._killShip(ship, ownerId, null);
      }
    }
    for (const t of this.turrets) {
      if (!t.alive) continue;
      const dist = Math.hypot(t.x - x, t.y - y);
      if (dist > radius) continue;
      const dmg = Math.round(damage * (1 - 0.5 * dist / radius));
      this._damageTurret(t, dmg, ownerId);
    }
    this.events.push({
      type: 'event', kind: 'explosion',
      x, y,
      size: radius > 80 ? 'large' : 'medium',
    });
  }

  /**
   * Apply environmental damage (black hole, energy wave): no kill credit.
   */
  _damageEnvironment(ship, dmg) {
    this._applyDamage(ship, dmg);
    if (ship.shield <= 0) {
      ship.shield = 0;
      this._killShip(ship, null, null);
    }
  }

  /**
   * Damage a turret; on destruction broadcast a large explosion and
   * maybe drop a random powerup at its position.
   */
  _damageTurret(turret, dmg, attackerId) {
    if (!turret.alive) return;
    turret.hp -= dmg;
    if (turret.hp > 0) return;
    turret.hp    = 0;
    turret.alive = false;
    this.events.push({
      type: 'event', kind: 'turret_destroyed',
      id: turret.id, x: turret.x, y: turret.y, killerId: attackerId,
    });
    this.events.push({
      type: 'event', kind: 'explosion',
      x: turret.x, y: turret.y, size: 'large',
    });
    if (Math.random() < CONFIG.POWERUP_DROP_CHANCE) {
      const typeId = Math.floor(Math.random() * CONFIG.POWERUPS.length);
      this.powerups.push(createPowerup(turret.x, turret.y, typeId));
    }
  }

  /**
   * Push new mines, enforcing CONFIG.MINE.MAX_PER_SHIP per owner
   * (the owner's oldest mine is dropped when the cap is exceeded).
   */
  _addMines(mines) {
    for (const m of mines) {
      this.mines.push(m);
      const owned = this.mines.filter(x => x.ownerId === m.ownerId);
      if (owned.length > CONFIG.MINE.MAX_PER_SHIP) {
        this.mines.splice(this.mines.indexOf(owned[0]), 1);
      }
    }
  }

  /** Push a lazer trap, enforcing LAZERTRAP.MAX_PER_SHIP (F11a). */
  _addLazerTrap(trap) {
    this.lazerTraps.push(trap);
    const owned = this.lazerTraps.filter(t => t.ownerId === trap.ownerId);
    if (owned.length > CONFIG.LAZERTRAP.MAX_PER_SHIP) {
      this.lazerTraps.splice(this.lazerTraps.indexOf(owned[0]), 1);
    }
    this.events.push({
      type: 'event', kind: 'explosion',
      x: trap.x1, y: trap.y1, size: 'small',
    });
  }

  /**
   * Resolve beam shots: damage the hit ship, always broadcast the beam
   * event so clients can render it.
   */
  _handleBeams(beams) {
    for (const b of beams) {
      if (b.hitShipId && this.ships[b.hitShipId]) {
        const ship = this.ships[b.hitShipId];
        const wDef = CONFIG.WEAPONS[b.weapon];
        this._applyDamage(ship, wDef.damage);
        ship.hitFlashTimer = 0.15;
        if (ship.shield <= 0) {
          ship.shield = 0;
          this._killShip(ship, b.ownerId, b.weapon);
        }
      }
      this.events.push({
        type: 'event', kind: 'beam',
        x1: b.x1, y1: b.y1, x2: b.x2, y2: b.y2,
        weapon: b.weapon,
      });
    }
  }

  _killShip(ship, killerId, weaponId) {
    ship.alive        = false;
    ship.respawnTimer = CONFIG.RESPAWN_TIME;
    ship.deaths++;

    if (killerId && this.ships[killerId]) {
      this.ships[killerId].kills++;
    }

    // Solo mode: player loses a life; AI respawn depends on sub-mode
    if (this.soloMode) {
      if (ship.isAI) {
        this.aiKilled++;
        ship.respawnTimer = this._aiShouldRespawn() ? CONFIG.RESPAWN_TIME : 9999;
      } else {
        this.playerLives = Math.max(0, this.playerLives - 1);
        if (this.playerLives <= 0) {
          ship.respawnTimer = 9999;  // no more respawns
        }
      }
    }

    this.events.push({
      type: 'event', kind: 'kill',
      killerId, victimId: ship.id,
      weapon: weaponId,
    });
    this.events.push({
      type: 'event', kind: 'explosion',
      x: ship.x, y: ship.y, size: 'large',
    });

    // Clear bullets owned by dead ship
    this.bullets = this.bullets.filter(b => b.ownerId !== ship.id);
  }

  _checkRoundEnd() {
    if (this.roundOver) return;

    if (this.soloMode) {
      // Defeat: out of lives and the human ship is gone
      if (this.playerLives <= 0) {
        const humanShip = Object.values(this.ships).find(s => !s.isAI);
        if (humanShip && !humanShip.alive) this._endSolo(false);
        return;
      }

      // Endless: no victory — only defeat (waves advance in _update)
      if (this.soloGameMode === 'endless') return;

      // Mission: objective-driven victory
      if (this.mission) {
        const obj = this.mission.objective;
        if (obj.type === 'eliminate' && this.aiKilled >= obj.kills) {
          this._endSolo(true);
          return;
        }
        if (obj.type === 'survive' && this.missionTimer <= 0) {
          this._endSolo(true);
          return;
        }
        if (obj.type === 'turrets' && this.turrets.length > 0 && this.turrets.every(t => !t.alive)) {
          this._endSolo(true);
          return;
        }
        return;
      }

      // Skirmish: all AI destroyed
      if (this.aiShips.length > 0 && this.aiShips.every(ai => !ai.alive)) {
        this._endSolo(true);
      }
      return;
    }

    for (const ship of Object.values(this.ships)) {
      if (ship.kills >= CONFIG.KILL_TARGET) {
        this.roundOver = true;
        const scores = Object.values(this.ships).map(s => ({
          id: s.id, name: s.name, kills: s.kills, deaths: s.deaths,
        }));
        this.broadcast({
          type:     'round_end',
          winnerId: ship.id,
          winnerName: ship.name,
          scores,
        });
        this._endTimeout = setTimeout(() => {
          if (!this.running) return;
          this.stop();
          this.room.state = 'lobby';
          this.room.game  = null;
          this.broadcast({ type: 'lobby_reset' });
        }, 5000);
        return;
      }
    }
  }

  /** Current solo score: endless = kills + wave bonus, otherwise kills × difficulty. */
  _soloScore() {
    const humanShip = Object.values(this.ships).find(s => !s.isAI);
    const kills = humanShip?.kills || 0;
    if (this.soloGameMode === 'endless') {
      return kills + WAVE_SCORE_BONUS * (this.wave - 1);
    }
    return kills * (SOLO_SCORE_MULT[this.soloDiff] || 1);
  }

  _endSolo(victory) {
    this.roundOver = true;
    const humanShip = Object.values(this.ships).find(s => !s.isAI);
    const kills  = humanShip?.kills  || 0;
    const deaths = humanShip?.deaths || 0;
    this.broadcast({
      type: 'solo_end', victory,
      score:       this._soloScore(),
      kills, deaths,
      difficulty:  this.soloDiff,
      livesLeft:   this.playerLives,
      mode:        this.soloGameMode,
      wave:        this.soloGameMode === 'endless' ? this.wave : null,
      missionId:   this.mission ? this.mission.id   : null,
      missionName: this.mission ? this.mission.name : null,
      // GAME OVER stats screen (CA Deluxe style)
      gameTime:    Math.round((Date.now() - this._startTime) / 1000),
      shotsFired:  humanShip?.shotsFired || 0,
      shotsHit:    humanShip?.shotsHit   || 0,
    });
    this._endTimeout = setTimeout(() => {
      if (!this.running) return;
      this.stop();
      this.room.state = 'lobby';
      this.room.game  = null;
    }, 5000);
  }

  _broadcastState() {
    const players = Object.values(this.ships).map(s => ({
      id:             s.id,
      name:           s.name,
      shipId:         s.shipId,
      isAI:           s.isAI || false,
      x:              s.x,
      y:              s.y,
      angle:          s.angle,
      vx:             s.vx,
      vy:             s.vy,
      shield:         s.shield,
      ammo:           s.ammo,
      weapon:         s.weapon,
      weapons:        s.weapons,
      modifiers:      s.modifiers,
      pshieldPool:    s.pshieldPool,
      dashing:        s.dashing,
      dodging:        s.dodging,
      thrusting:      s.thrusting,
      alive:          s.alive,
      invulnerable:   s.invulnerable,
      respawnTimer:   s.respawnTimer,
      hitFlashTimer:  s.hitFlashTimer,
      dashCooldown:   s.dashCooldown,
      dodgeCooldown:  s.dodgeCooldown,
      onRefuel:       s.onRefuel,
      angularVel:     s.angularVel,
      kills:          s.kills,
      deaths:         s.deaths,
      speedBoostTimer: s.speedBoostTimer,
    }));

    const bullets = this.bullets.map(b => ({
      id:     b.id,
      x:      b.x,
      y:      b.y,
      vx:     b.vx,
      vy:     b.vy,
      weapon: b.weapon,
      size:   b.size,
    }));

    const powerups = this.powerups.map(p => ({
      id:       p.id,
      x:        p.x,
      y:        p.y,
      typeId:   p.typeId,
      icon:     p.icon,
      color:    p.color,
      bobPhase: p.bobPhase,
    }));

    const mines = this.mines.map(m => ({
      id:      m.id,
      x:       m.x,
      y:       m.y,
      ownerId: m.ownerId,
      armed:   m.armTimer <= 0,
    }));

    let soloInfo = null;
    if (this.soloMode) {
      soloInfo = {
        mode:        this.soloGameMode,
        lives:       this.playerLives,
        aiRemaining: this.aiShips.filter(ai => ai.alive).length,
        wave:        this.soloGameMode === 'endless' ? this.wave : null,
        score:       this._soloScore(),
        objective:   null,
      };
      if (this.mission) {
        const obj = this.mission.objective;
        if (obj.type === 'eliminate') {
          soloInfo.objective = { text: 'KILLS', progress: this.aiKilled, target: obj.kills };
        } else if (obj.type === 'turrets') {
          soloInfo.objective = {
            text:     'TURRETS',
            progress: this.turrets.filter(t => !t.alive).length,
            target:   this.turrets.length,
          };
        } else if (obj.type === 'survive') {
          soloInfo.objective = {
            text:     'SURVIVE',
            progress: Math.ceil(Math.max(0, this.missionTimer)),
            target:   obj.seconds,
          };
        }
      }
    }

    const turrets = this.turrets.map(t => ({
      id:    t.id,
      type:  t.type,
      x:     t.x,
      y:     t.y,
      angle: t.angle,
      hp:    t.hp,
      alive: t.alive,
    }));

    const wave = this.waveState && this.waveState.active
      ? { axis: this.waveState.axis, pos: this.waveState.active.pos, dir: this.waveState.active.dir }
      : null;

    // F7b: door open fractions (per group) + piston block positions
    const doors = Object.entries(this.doorState).map(([group, d]) => ({
      group: Number(group), open: d.open, frac: d.frac,
    }));
    const pistons = this.pistons.map(p => ({ x: p.x, y: p.y, phase: p.phase }));

    // F11a: sticky bombs (posizione risolta) + lazer traps attive
    const stickies = this.stickies.map(s => ({
      x: s.targetId && this.ships[s.targetId] ? this.ships[s.targetId].x : s.x,
      y: s.targetId && this.ships[s.targetId] ? this.ships[s.targetId].y : s.y,
      timer: s.timer,
    }));
    const lazerTraps = this.lazerTraps.map(t => ({ x1: t.x1, y1: t.y1, x2: t.x2, y2: t.y2 }));

    // F7c: posizione/angolo dei path vehicles
    const pathVehicles = this.pathVehicles.map(v => ({ x: v.x, y: v.y, angle: v.angle }));

    this.broadcast({
      type:    'state',
      tick:    this.tickCount,
      players,
      bullets,
      mines,
      powerups,
      soloInfo,
      turrets,
      wave,
      doors,
      pistons,
      stickies,
      lazerTraps,
      pathVehicles,
    });
  }
}

/** Distance from point (px,py) to segment (x1,y1)-(x2,y2). */
function _distToSegment(px, py, x1, y1, x2, y2) {
  const dx = x2 - x1, dy = y2 - y1;
  const len2 = dx * dx + dy * dy;
  let t = len2 > 0 ? ((px - x1) * dx + (py - y1) * dy) / len2 : 0;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(px - (x1 + t * dx), py - (y1 + t * dy));
}

export default Game;
export { waveComposition };
