// AUTO-GENERATED by server/build-sim.mjs — DO NOT EDIT (source: server/src/matchlog.js)
// Re-run `npm run build:sim` in server/ after changing the source.

// No-op browser stub: il match log esiste solo lato server (fs).
export function logMatch() {}
