// AUTO-GENERATED by server/build-sim.mjs — DO NOT EDIT (source: server/src/missions.js)
// Re-run `npm run build:sim` in server/ after changing the source.

// server/src/missions.js — handcrafted single-player mission definitions

'use strict';

// Objective types:
//   eliminate { type, kills }   — destroy N AI ships (no AI respawn)
//   survive   { type, seconds } — stay alive T seconds (AI respawn)
//   turrets   { type }          — destroy every turret in the arena
const MISSIONS = [
  {
    id:         'first-blood',
    name:       'FIRST BLOOD',
    desc:       'Destroy 3 enemy ships',
    arenaId:    'training-grounds',
    difficulty: 'easy',
    lives:      3,
    aiCount:    3,
    objective:  { type: 'eliminate', kills: 3 },
  },
  {
    id:         'crossfire-arena',
    name:       'CROSSFIRE ARENA',
    desc:       'Destroy 5 enemy ships',
    arenaId:    'crossfire',
    difficulty: 'medium',
    lives:      3,
    aiCount:    3,   // 3 at a time, 5 kills total → AI respawn until target met
    objective:  { type: 'eliminate', kills: 5 },
  },
  {
    id:         'acid-test',
    name:       'ACID TEST',
    desc:       'Survive 60 seconds',
    arenaId:    'acid-baths',
    difficulty: 'medium',
    lives:      3,
    aiCount:    2,
    objective:  { type: 'survive', seconds: 60 },
  },
  {
    id:         'mine-sweeper',
    name:       'MINE SWEEPER',
    desc:       'Destroy 5 enemy ships',
    arenaId:    'minefield',
    difficulty: 'medium',
    lives:      3,
    aiCount:    3,
    objective:  { type: 'eliminate', kills: 5 },
  },
  {
    id:         'turret-hunter',
    name:       'TURRET HUNTER',
    desc:       'Destroy all turrets',
    arenaId:    'turret-ally',
    difficulty: 'hard',
    lives:      3,
    aiCount:    2,
    objective:  { type: 'turrets' },
  },
  {
    id:         'event-horizon',
    name:       'EVENT HORIZON',
    desc:       'Survive 90 seconds',
    arenaId:    'black-hole-sun',
    difficulty: 'hard',
    lives:      3,
    aiCount:    3,
    objective:  { type: 'survive', seconds: 90 },
  },
];

function getMission(id) {
  return MISSIONS.find(m => m.id === id) || null;
}

// Shape sent to the client for the mission picker
function missionList() {
  return MISSIONS.map(m => ({
    id:         m.id,
    name:       m.name,
    desc:       m.desc,
    difficulty: m.difficulty,
  }));
}

export { MISSIONS, getMission, missionList };
