// client/js/offline.js — Offline solo mode (F8)
//
// Runs the SAME authoritative Game class used by the server, but locally in
// the browser (ESM build generated by server/build-sim.mjs into client/js/sim/).
// No network is involved: Game's broadcast() messages are dispatched straight
// to the same handlers main.js uses for server messages.

import Game from './sim/game.js';
import { missionList } from './sim/missions.js';
import { arenaList } from './sim/arenas.js';

export const OFFLINE_PLAYER_ID = 'offline-player';

// Offline replacements for the lists the server normally sends in `welcome`
export function offlineMissionList() { return missionList(); }
export function offlineArenaList()   { return arenaList(); }

let current = null;   // { game }

/**
 * Start a local solo game.
 * options: { mode, difficulty, arenaId, missionId, ship, name, onMessage }
 *   onMessage(msg) receives every Game broadcast ('arena' synchronously on
 *   start, then 'state' / 'event' / 'solo_end' from the 60Hz loop).
 * Returns the Game instance (feed input via game.receiveInput).
 */
export function startOfflineGame({ mode, difficulty, arenaId, missionId, ship, name, onMessage }) {
  stopOfflineGame();

  const room    = { code: 'OFFLINE', state: 'playing', game: null };
  const players = [{ id: OFFLINE_PLAYER_ID, name, ship }];
  const game = new Game(room, players, onMessage, {
    soloMode:   true,
    difficulty: difficulty || 'easy',
    arenaId:    arenaId || 'random',
    mode:       mode || 'skirmish',
    missionId,
  });
  room.game = game;
  current = { game };

  game.start();   // broadcasts 'arena' synchronously, then ticks at 60Hz
  return game;
}

export function stopOfflineGame() {
  if (!current) return;
  current.game.stop();
  current = null;
}

export function getOfflineGame() {
  return current ? current.game : null;
}
