// server/build-sim.mjs — generate the browser (ESM) build of the game simulation
//
// Reads the pure-logic CommonJS modules from server/src/ and emits equivalent
// ES modules into client/js/sim/ so the client can run the SAME Game class
// locally (offline solo mode, feature F8). No dependencies, run with:
//
//   node build-sim.mjs        (or: npm run build:sim)
//
// Conversion rules:
//   require('./x')                      → import from './x.js'
//   require('./config') / ../../shared/config.js → import CONFIG from './config.js'
//   module.exports = { ... }            → export { ... }
//   module.exports = Game (+ .waveComposition)  → export default Game + named export
//   process.hrtime.bigint()             → nowMs() (performance.now() in ns)
//   shared/config.js                    → export default window.CONFIG
//
// The generated files are committed to the repo; re-run this script whenever
// server/src/ logic changes.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const SRC  = path.join(ROOT, 'server', 'src');
const OUT  = path.join(ROOT, 'client', 'js', 'sim');

// Order matters only for readability of the log
const MODULES = [
  'arena', 'arenas', 'physics', 'weapons', 'enemies',
  'powerups', 'hazards', 'missions', 'game',
];

const HEADER = (src) =>
  `// AUTO-GENERATED by server/build-sim.mjs — DO NOT EDIT (source: ${src})\n` +
  `// Re-run \`npm run build:sim\` in server/ after changing the source.\n\n`;

function transform(source, name) {
  let out = source;

  // CONFIG imports (both spellings) → the sim config module
  out = out.replace(
    /const\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*['"](?:\.\/config|\.\.\/\.\.\/shared\/config(?:\.js)?)['"]\s*\)\s*;?/g,
    `import $1 from './config.js';`
  );

  // destructured relative requires → named ESM imports (with .js extension)
  out = out.replace(
    /const\s+(\{[^}]+\})\s*=\s*require\(\s*['"]\.\/(\w+)['"]\s*\)\s*;?/g,
    `import $1 from './$2.js';`
  );

  // module.exports = { a, b, ... } → export { a, b, ... }
  out = out.replace(
    /module\.exports\s*=\s*\{([^}]*)\}\s*;?/g,
    `export {$1};`
  );

  if (name === 'game') {
    // class default export + named waveComposition
    out = out.replace(
      /module\.exports\s*=\s*Game\s*;\s*\nmodule\.exports\.waveComposition\s*=\s*waveComposition\s*;?/,
      'export default Game;\nexport { waveComposition };'
    );
    // Browser-safe clock: performance.now() (ms) → nanoseconds, same scale
    // as process.hrtime.bigint(), so `Number(now - last) / 1e9` is unchanged.
    out = out.replaceAll('process.hrtime.bigint()', 'nowMs()');
    out = out.replace(
      'const TICK_MS =',
      'const nowMs = () => performance.now() * 1e6;\n\nconst TICK_MS ='
    );
  }

  // Sanity: nothing Node/CommonJS-specific may survive the conversion
  const leftovers = out.match(/require\(|module\.exports|process\./g);
  if (leftovers) {
    throw new Error(`${name}: conversion incomplete, leftovers: ${[...new Set(leftovers)].join(', ')}`);
  }
  return out;
}

mkdirSync(OUT, { recursive: true });

// 1. CONFIG shim: the classic script /js/config.js sets window.CONFIG
writeFileSync(
  path.join(OUT, 'config.js'),
  HEADER('shared/config.js') +
  `// Single source of truth: shared/config.js, served at /js/config.js as a\n` +
  `// classic script that sets window.CONFIG before any module loads.\n` +
  `export default window.CONFIG;\n`
);

// 2. package.json so Node treats the generated .js files as ES modules (tests)
writeFileSync(
  path.join(OUT, 'package.json'),
  JSON.stringify({ type: 'module' }, null, 2) + '\n'
);

// 3. Simulation modules
for (const name of MODULES) {
  const src = readFileSync(path.join(SRC, name + '.js'), 'utf8');
  const esm = transform(src, name);
  writeFileSync(path.join(OUT, name + '.js'), HEADER(`server/src/${name}.js`) + esm);
  console.log(`sim/${name}.js  (${esm.length} bytes)`);
}

console.log(`\nDone — ${MODULES.length + 2} files written to client/js/sim/`);
